### ISSUE TITLE
[Question] Content covers setting up VSCode in debug mode?

### ISSUE THREAD

**Issue by scheung38** [mikeckennedy/cookiecutter-course#20]
Hello didn't see this being mentioned but is there tutorial on that as this is likely the most important piece in production development

**Comment by mikeckennedy** [comment]
Hi @scheung38 No we use PyCharm in this course. But there is lots of info on running Python in VS Code and that should work in this course:

https://code.visualstudio.com/docs/python/debugging

Enjoy.
